"""some changes

Revision ID: 64807b9603a8
Revises: 2d1c5cabceb6
Create Date: 2023-09-08 16:11:31.516063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64807b9603a8'
down_revision = '2d1c5cabceb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
